const express=require('express'),http=require('http'),path=require('path');const {Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname,'public')));
const rooms=new Map(),alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',shapes=['●','▲','■','◆','★','✚','⬟','⬢'],colors=['#ff4d6d','#4dabf7','#51cf66','#ffd43b','#845ef7','#ff922b'];
function code(){let c;do{c=Array.from({length:6},()=>alphabet[Math.floor(Math.random()*alphabet.length)]).join('')}while(rooms.has(c));return c}
function state(r){return{code:r.code,hostId:r.hostId,phase:r.phase,round:r.round,players:[...r.players.values()]}}
function emit(r){io.to(r.code).emit('room:update',state(r))}
function makeRound(round){const chaos=round>=8,challenge=round>=4,target=shapes[Math.floor(Math.random()*shapes.length)],count=challenge?56:36,cells=[],positions=new Set(),multi=chaos&&round%2===0;while(positions.size<(multi?2:1))positions.add(Math.floor(Math.random()*count));for(let i=0;i<count;i++){const targetCell=positions.has(i),shape=targetCell?target:shapes[Math.floor(Math.random()*shapes.length)];cells.push({id:i,shape,color:colors[Math.floor(Math.random()*colors.length)],target:targetCell,x:8+Math.random()*84,y:8+Math.random()*84,size:challenge?20+Math.random()*10:26+Math.random()*12})}let twist='Find the target';if(chaos){twist=['Find the target','Double Hunt','Reverse Hunt','Color Trap','Lightning Round'][Math.floor(Math.random()*5)];if(twist==='Reverse Hunt')cells.forEach(c=>c.target=!c.target);if(twist==='Color Trap'){const wanted=cells.find(c=>c.target).color;cells.forEach(c=>c.target=c.color===wanted)}}return{round,target,cells,twist,duration:twist==='Lightning Round'?3000:10000}}
function finish(r){if(!rooms.has(r.code)||r.phase!=='playing')return;r.phase='results';const entries=[...r.responses.values()].sort((a,b)=>a.ms-b.ms),pts=[100,80,60];entries.forEach((e,i)=>{const p=r.players.get(e.id);if(p&&e.correct)p.score+=pts[i]??40});r.players.forEach(p=>{const e=r.responses.get(p.id);if(e&&!e.correct)p.score-=10});io.to(r.code).emit('round:results',{entries:entries.map((e,i)=>({name:r.players.get(e.id)?.name,correct:e.correct,ms:e.ms,points:e.correct?(pts[i]??40):-10})),state:state(r)});emit(r);if(r.round>=10){r.phase='finished';const winner=[...r.players.values()].sort((a,b)=>b.score-a.score)[0];io.to(r.code).emit('game:finished',{winner:winner?.name,players:[...r.players.values()].sort((a,b)=>b.score-a.score)});emit(r)}}
function start(r){r.phase='playing';r.round++;r.data=makeRound(r.round);r.responses=new Map();r.startedAt=Date.now();io.to(r.code).emit('round:start',r.data);clearTimeout(r.timer);r.timer=setTimeout(()=>finish(r),r.data.duration+100)}
io.on('connection',s=>{s.on('room:create',({name},cb)=>{const c=code(),r={code:c,hostId:s.id,phase:'lobby',round:0,players:new Map(),responses:new Map()};r.players.set(s.id,{id:s.id,name:String(name||'Player').slice(0,18),score:0});rooms.set(c,r);s.join(c);cb({ok:true,code:c});emit(r)});s.on('room:join',({code:c,name},cb)=>{c=String(c||'').toUpperCase();const r=rooms.get(c);if(!r)return cb({ok:false,error:'Room not found'});if(r.players.size>=8)return cb({ok:false,error:'Room is full'});if(r.phase!=='lobby')return cb({ok:false,error:'Game already started'});r.players.set(s.id,{id:s.id,name:String(name||'Player').slice(0,18),score:0});s.join(c);cb({ok:true,code:c});emit(r)});s.on('game:start',({code:c})=>{const r=rooms.get(String(c||'').toUpperCase());if(r&&r.hostId===s.id&&r.players.size>=2)start(r)});s.on('round:answer',({code:c,cellId})=>{const r=rooms.get(String(c||'').toUpperCase());if(!r||r.phase!=='playing'||r.responses.has(s.id))return;const cell=r.data.cells.find(x=>x.id===cellId);r.responses.set(s.id,{id:s.id,correct:!!cell?.target,ms:Date.now()-r.startedAt});if(r.responses.size===r.players.size)finish(r)});s.on('round:next',({code:c})=>{const r=rooms.get(String(c||'').toUpperCase());if(r&&r.hostId===s.id&&r.phase==='results'&&r.round<10)start(r)});s.on('disconnect',()=>{for(const[c,r]of rooms){if(!r.players.has(s.id))continue;r.players.delete(s.id);if(r.hostId===s.id)r.hostId=r.players.keys().next().value;if(!r.players.size){clearTimeout(r.timer);rooms.delete(c)}else emit(r)}})});
server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('Target Hunt running'));
